spring.application.name=taskrestapi
spring.datasource.url = jdbc:mysql://localhost:3306/tasks 
spring.datasource.username = root
spring.datasource.password = nk8098@21
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
server.port = 9005
